import {useState} from 'react';
import {Link,NavLink,useNavigate} from 'react-router-dom';
import {House,Menu,X,ArrowUpRight,Bell,LogOut} from 'lucide-react';
import {useAuth} from '../../context/AuthContext';
import {useNotifications} from '../../context/NotificationContext';
export function Logo(){return <Link className="logo" to="/"><span><House size={23}/></span>Board<span className="logo-lk">LK</span><small>FIND YOUR PLACE</small></Link>;}
export function NotificationDropdown(){const [open,setOpen]=useState(false);const {notifications,unread,markRead,markAllRead}=useNotifications();const {user}=useAuth();return <div className="notification-wrap"><button className="icon-button" aria-label={'Notifications, '+unread+' unread'} aria-expanded={open} onClick={()=>setOpen(!open)}><Bell size={18}/>{unread>0&&<i className="notification-dot"/>}</button>{open&&<div className="notification-dropdown"><div className="section-heading"><h3>Notifications</h3><button className="text-link" onClick={markAllRead}>Read all</button></div>{notifications.slice(0,4).map(n=><Link to={n.path} key={n.id} className="notification-item" onClick={()=>{markRead(n.id);setOpen(false);}}><b>{n.title}</b><p>{n.body}</p></Link>)}{!notifications.length&&<p>You are all caught up.</p>}<Link className="text-link" to={'/'+user.role+'/notifications'} onClick={()=>setOpen(false)}>View all notifications →</Link></div>}</div>;}
export function MobileMenu({onClose}){const {user,logout}=useAuth();const navigate=useNavigate();return <div className="mobile-menu"><NavLink to="/" onClick={onClose}>Home</NavLink><NavLink to="/properties" onClick={onClose}>Find Boarding</NavLink><NavLink to="/map" onClick={onClose}>Explore Map</NavLink>{user?<><NavLink to={'/'+user.role+'/dashboard'} onClick={onClose}>Dashboard</NavLink>{(user.role==='owner'?[['properties','My Properties'],['bookings','Booking Requests']]:[['favorites','Favorites'],['bookings','Bookings']]).concat([['messages','Messages'],['profile','Profile']]).map(([p,label])=><NavLink key={p} to={'/'+user.role+'/'+p} onClick={onClose}>{label}</NavLink>)}<button onClick={()=>{logout();onClose();navigate('/');}}>Logout</button></>:<><Link to="/login" onClick={onClose}>Log in</Link><Link to="/register" onClick={onClose}>Get started</Link></>}</div>;}
export function Navbar(){const {user,logout}=useAuth();const [open,setOpen]=useState(false);const navigate=useNavigate();return <header className="navbar"><div className="container nav-inner"><Logo/><nav className="desktop-nav" aria-label="Main navigation"><NavLink to="/" end>Home</NavLink><NavLink to="/properties">Find Boarding</NavLink><NavLink to="/map">Explore Map</NavLink>{user&&<NavLink to={'/'+user.role+'/dashboard'}>Dashboard</NavLink>}</nav><div className="nav-actions">{user?<><NotificationDropdown/><Link className="btn small secondary desktop-only" to={'/'+user.role+'/profile'}>{user.name.split(' ')[0]}</Link><button className="icon-button desktop-only" aria-label="Logout" onClick={()=>{logout();navigate('/');}}><LogOut size={17}/></button></>:<><Link className="text-link desktop-only" to="/login">Log in</Link><Link className="btn small" to="/register">Get started <ArrowUpRight size={15}/></Link></>}<button className="icon-button mobile-toggle" aria-label={open?'Close menu':'Open menu'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></div>{open&&<MobileMenu onClose={()=>setOpen(false)}/>}</header>;}
export function Footer(){return <footer><div className="container footer-grid"><div><Logo/><p>Your next chapter starts with the right place.<br/>Discover a space to call home in Sri Lanka.</p><span className="footer-made">Made for life in Sri Lanka 🇱🇰</span></div><div><h4>Explore</h4><Link to="/properties">Find boarding</Link><Link to="/map">Explore the map</Link><Link to="/properties?q=Colombo">Boarding in Colombo</Link><Link to="/properties?q=Vavuniya">Boarding in Vavuniya</Link></div><div><h4>For you</h4><Link to="/register?role=renter">Become a renter</Link><Link to="/register?role=owner">List your property</Link><Link to="/login">Your account</Link><Link to="/forgot-password">Account help</Link></div><div><h4>A better way to find home.</h4><p>From campus life to your next career move, find a place that fits.</p><Link className="text-link" to="/properties">Start exploring <ArrowUpRight size={15}/></Link></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} BoardLK. All rights reserved.</span><span>Thoughtfully connecting people & places.</span></div></footer>;}

